### ISSUE TITLE
Dynamic adding CompiledRazorItems

### ISSUE THREAD

**Issue by yang-er** [lamondlu/Mystique#1]
我在[自己的项目](https://github.com/yang-er/OnlineJudge/tree/master/JudgeWeb.Features.AspNetCore/AppPart)中尝试了将Area分到其他程序集中，然后发现可以通过[给RazorViewEngineOptions添加其他的FileProvider、使用自己编写RazorCompiledItemLoader](https://github.com/yang-er/OnlineJudge/blob/8c5c0874fa25cd5a2cfceb79b0906fc41fda98c2/JudgeWeb.Features.AspNetCore/Mvc/Extensions.cs#L80)以支持从其他项目文件夹中监测cshtml动态修改。

今日重新阅读了您的第三篇文章，见到您说不能动态加载RazorCompiledItemAssembly，然后尝试在我自己的那个Loader中加了个throw来寻找调用堆栈。

```
System.Exception: Exception of type 'System.Exception' was thrown.
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AreaRazorAssemblyPart.Microsoft.AspNetCore.Mvc.ApplicationParts.IRazorCompiledItemProvider.get_CompiledItems() in C:\Users\tlylz\Source\Repos\OnlineJudge\JudgeWeb.Features.AspNetCore\AppPart\AreaRazorAssemblyPart.cs:line 27
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RazorCompiledItemFeatureProvider.PopulateFeature(IEnumerable`1 parts, ViewsFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.CompiledPageRouteModelProvider.GetViewFeature(ApplicationPartManager applicationManager)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.CompiledPageRouteModelProvider.GetViewDescriptors(ApplicationPartManager applicationManager)+MoveNext()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.CompiledPageRouteModelProvider.CreateModels(PageRouteModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.CompiledPageRouteModelProvider.OnProvidersExecuting(PageRouteModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
```

（有行号的是我自己的代码，不是官方的，我个人比较喜欢把这种Infra放到和官方命名空间里一样的位置。）

实际上IActionDescriptorChangeProvider的Token被激活以后，我的`AreaRazorAssemblyPart`是被重新执行了一遍的。所以猜想，您的第三篇文章中加载失败的问题，可能和`CompiledRazorAssemblyPart`有关系。

**Comment by yang-er** [comment]
我对这个问题的猜想是

1. 加载了CompiledRazorAssembly也就是.Views.dll

2. 发现checksum不一致（因为实际Plugin的cshtml不在主项目的FileProvider中）

3. 运行时尝试重新编译RazorItem，然后编译失败，因为找不到文件。

**Comment by lamondlu** [comment]
谢谢反馈，我问题很有可能是和说你的情况一样。
如果产生相同的checksum就可以，跳过razorItem的重新编译了

这块我再查阅一下源码，看看能不能解决。

**Comment by yang-er** [comment]
按理来说，它应该不能重新编译就用已经编译过的。可能和项目编译设置有关系？
感觉可能需要override一下那个CompiledRazorAssemblyPart和RazorCompiledItem，追踪一下究竟有没有被触发。

另外RazorCompiledItem里面有个属性Identifier，它是用来表示这个CompiledItem来自于哪个cshtml，并且RazorSourceChecksumAttribute里面也会有一个cshtml的路径，运行时会到FileProvider中注册文件系统的ChangeToken，这是我理解的动态修改cshtml的实现方式。

**Comment by XCStar** [comment]
我发现CompiledRazorAssembly可以加载视图，和不编译一样把视图文件复制过来就能正确访问。而且不重新编译Plugin1改了Plugin1复制过来的视图文件内容之后，重启之后页面是改变之后的内容。看来视图编译和想象的编译有区别别

**Comment by XCStar** [comment]
内容变化是用了3.0的原因,用2.2内容不会变化视图能正确访问

**Comment by lamondlu** [comment]
> 内容变化是用了3.0的原因,用2.2内容不会变化视图能正确访问

3.0有RuntimeCompilation, 所以内容会变化。当前项目我已经升级到.NET Core 3.0, 但是还是有坑要填

**Comment by lamondlu** [comment]
https://www.cnblogs.com/lwqlun/p/13992077.html
